import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Neutral Farming Assignment',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          href='https://api.tiles.mapbox.com/mapbox-gl-js/v<YOUR_MAPBOX_VERSION>/mapbox-gl.css'
          rel='stylesheet'
        />
      </head>
      <body className={inter.className}>
        <main className='flex min-h-screen flex-col w-full items-center gap-8 p-8'>
          <div className='flex justify-between items-center pl-16 pr-24 w-full py-4 rounded-lg bg-green-600/30 shadow-lg shadow-green-950'>
            <div className='flex flex-col gap-2'>
              <h1 className='text-5xl font-bold text-teal-200'>⛰️Soiler</h1>
              <h2 className='text-2xl font-semibold text-teal-300'>
                Your soil data saver
              </h2>
            </div>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
